ncliente = input("Digite o nome do cliente: ")
dvencimento = input("Digite o dia de vencimento: ")
mvencimento = input("Digite o mês de vencimento: ")
vfatura = input("Digite o valor da fatura: ")
print("Olá", ncliente)
print("A sua fatura com vencimento em", dvencimento ,"de", mvencimento ,"no valor de R$",vfatura, "está fechada.")
